<a href="https://colab.research.google.com/github/ShrayankM/FoundationsOFDataScience/blob/master/Basics_Of_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Checking Performance of Lists

In [0]:
N = 100000000

In [2]:
%%time
list_ = list(range(N))
for i in range(N):
    list_[i] = list_[i] * list_[i]

CPU times: user 19.2 s, sys: 2.47 s, total: 21.7 s
Wall time: 21.7 s


In [3]:
%%time
list_ = list(range(N))
list_ = [item * item for item in list_]

CPU times: user 9.2 s, sys: 5.67 s, total: 14.9 s
Wall time: 14.9 s


In [4]:
%%time
list_ = list(range(N))
list_ = map(lambda x: x * x,list_)

CPU times: user 2.35 s, sys: 1.95 s, total: 4.3 s
Wall time: 4.29 s


In [5]:
%%time
list_ = list(range(N))
list_sum = 0
for i in range(N):
    list_sum = list_sum + list_[i]

CPU times: user 15.7 s, sys: 1.53 s, total: 17.2 s
Wall time: 17.3 s


In [6]:
%%time
list_ = list(range(N))
list_sum = sum(list_)

CPU times: user 5.39 s, sys: 1.95 s, total: 7.34 s
Wall time: 7.32 s


In [0]:
import numpy as np

In [8]:
%%time
arr = np.arange(N)
arr = arr * arr

CPU times: user 441 ms, sys: 7.86 ms, total: 449 ms
Wall time: 452 ms


In [9]:
%%time
arr = np.arange(N)
arr_sum = np.sum(arr)

CPU times: user 317 ms, sys: 9.1 ms, total: 326 ms
Wall time: 326 ms


#Creating Numpy Arrays

In [10]:
arr = np.arange(5)
print(arr,type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [0]:
arr = np.array([0,2,4,6,8])

In [12]:
arr.dtype #tells the type of data items stored by arr

dtype('int64')

In [13]:
arr.ndim #show number of dimensions

1

In [14]:
arr.shape

(5,)

In [15]:
arr.size #total no of elements in array

5

In [16]:
arr.itemsize #no. of bytes required to store one data item in array(8-Bytes for integer)

8

In [0]:
arr = np.array([0.0,2,4,6,8])

In [18]:
arr.dtype

dtype('float64')

In [0]:
arr2d = np.array([
                  [1,2,3],
                  [4,5,6],
])

In [20]:
arr2d.shape #newly added dimension comes first

(2, 3)

In [0]:
arr3d = np.array([
                  [
                   [1,2,3],
                   [4,5,6],
                   [7,8,9]
                  ],
                  [
                   [10,11,12],
                   [13,14,15],
                   [16,17,18]
                  ],
])

In [22]:
arr3d.ndim

3

In [23]:
arr3d.shape

(2, 3, 3)

In [24]:
np.ones((3,4)) #takes argument as shape of ndArray

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
5 * np.ones((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [26]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [27]:
np.random.randn(2,3) #distributes the number in a normal distribution with data having (mean 0) and (variance 1)

array([[0.65000345, 1.07354119, 0.32595546],
       [0.83079233, 0.76939418, 0.43627447]])

In [28]:
np.random.randn(2,3,3)

array([[[-0.20626434,  2.3783404 , -0.78217718],
        [ 0.45170659,  0.72052917,  0.96273599],
        [-1.38561825,  1.2365634 , -0.02206643]],

       [[-2.07432975,  0.46584219, -0.63790725],
        [ 1.61813608, -1.01648763, -1.11075665],
        [-0.79504323,  0.40092815, -0.35112612]]])

In [29]:
np.random.rand(2,3) #random numbers between 0 and 1 in the given shape

array([[0.61487746, 0.53063183, 0.4176896 ],
       [0.01449897, 0.48313605, 0.12226064]])

In [30]:
np.random.rand(1,10)

array([[0.86829645, 0.04221497, 0.67812302, 0.60691486, 0.38649618,
        0.54718015, 0.98166122, 0.91107395, 0.88588833, 0.26958557]])

In [31]:
np.random.randint(0,100,(2,3)) #random integers between 0 and 100 in the given shape (2,3)

array([[ 4, 88, 11],
       [60, 56,  5]])

In [32]:
np.arange(7,71,7) #arg1 - smallNumber , arg2 - biggerNumber, arg3 - stepSize

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [33]:
np.linspace(7,70,10) #linearaly separated 5 numbers between 0 and 10

array([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70.])

In [34]:
str_arr = np.array(['1.2','2.4','4.5','6.6','9.5'])
float_arr = np.array(str_arr,dtype=float)
float_arr.dtype

dtype('float64')

#Indexing

In [0]:
arr3d = np.array([
                  [
                   [1,2,3],
                   [4,5,6],
                   [7,8,9]
                  ],
                  [
                   [10,11,12],
                   [13,14,15],
                   [16,17,18]
                  ],
])

In [45]:
arr3d[0,0,0]

1

In [46]:
arr3d[0,:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
arr3d[:,:,0:2] #maintains shape

array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8]],

       [[10, 11],
        [13, 14],
        [16, 17]]])

In [49]:
arr3d % 2 == 0 #creates a boolean array with True values for even numbers

array([[[False,  True, False],
        [ True, False,  True],
        [False,  True, False]],

       [[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]]])

In [50]:
arr3d[arr3d % 2 == 0] #shows all thoes values where given condition is True

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [52]:
arr3d[(arr3d % 2 == 1) & (arr3d > 3)]

array([ 5,  7,  9, 11, 13, 15, 17])

In [0]:
arr_slice = arr3d[:,:,0:2]

In [56]:
arr_slice

array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8]],

       [[10, 11],
        [13, 14],
        [16, 17]]])

In [55]:
arr_slice.shape

(2, 3, 2)

In [0]:
arr_slice[0,0,0] = 1729 #updates the slice and the main ndArray as well

In [58]:
arr_slice

array([[[1729,    2],
        [   4,    5],
        [   7,    8]],

       [[  10,   11],
        [  13,   14],
        [  16,   17]]])

In [59]:
arr3d

array([[[1729,    2,    3],
        [   4,    5,    6],
        [   7,    8,    9]],

       [[  10,   11,   12],
        [  13,   14,   15],
        [  16,   17,   18]]])

In [0]:
arr_slice = np.copy(arr3d[:,:,0:2]) #creates a new reference copy

In [61]:
arr_slice

array([[[1729,    2],
        [   4,    5],
        [   7,    8]],

       [[  10,   11],
        [  13,   14],
        [  16,   17]]])

In [0]:
arr_slice[0,0,0] = 1

In [63]:
arr_slice

array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8]],

       [[10, 11],
        [13, 14],
        [16, 17]]])

In [64]:
arr3d

array([[[1729,    2,    3],
        [   4,    5,    6],
        [   7,    8,    9]],

       [[  10,   11,   12],
        [  13,   14,   15],
        [  16,   17,   18]]])

In [0]:
arr = np.random.randint(0,10,5)

In [66]:
arr

array([7, 0, 9, 4, 9])

In [69]:
my_indices = [1,3,4]
arr[my_indices] #gives the values specified by the list my_indices

array([0, 4, 9])

#Numpy Operations

In [0]:
arr1 = np.random.rand(3,4)
arr2 = np.random.rand(3,4)

In [81]:
arr1

array([[0.0745992 , 0.35941613, 0.70714935, 0.76173848],
       [0.72361971, 0.88962655, 0.53011508, 0.47121318],
       [0.18346117, 0.21283983, 0.86691934, 0.30748805]])

In [82]:
arr2

array([[0.04988512, 0.7169955 , 0.45764222, 0.76527525],
       [0.97428146, 0.69145651, 0.53274996, 0.99231593],
       [0.22582877, 0.52921956, 0.1932074 , 0.22912611]])

In [83]:
arr1 + arr2

array([[0.12448432, 1.07641163, 1.16479157, 1.52701372],
       [1.69790117, 1.58108305, 1.06286504, 1.46352911],
       [0.40928994, 0.74205939, 1.06012675, 0.53661416]])

In [84]:
arr1 - arr2

array([[ 0.02471408, -0.35757937,  0.24950713, -0.00353677],
       [-0.25066175,  0.19817004, -0.00263488, -0.52110275],
       [-0.04236759, -0.31637973,  0.67371194,  0.07836194]])

In [85]:
arr1 * arr2

array([[0.00372139, 0.25769975, 0.3236214 , 0.5829396 ],
       [0.70500927, 0.61513806, 0.28241879, 0.46759234],
       [0.04143081, 0.112639  , 0.16749524, 0.07045354]])

In [86]:
np.exp(arr1) #exponent every value in numpy array

array([[1.07745222, 1.43249278, 2.02820132, 2.1419968 ],
       [2.06188314, 2.43422041, 1.69912783, 1.60193645],
       [1.20136832, 1.23718648, 2.37956891, 1.36000456]])

In [87]:
np.log(arr1) #take logarithm of each value

array([[-2.5956255 , -1.02327442, -0.34651339, -0.27215199],
       [-0.32348929, -0.11695351, -0.63466116, -0.75244468],
       [-1.69575221, -1.54721536, -0.14280934, -1.17931905]])

In [0]:
arr_inv = 1 / arr1

In [89]:
arr_inv

array([[13.4049695 ,  2.78229025,  1.41412843,  1.31278651],
       [ 1.38194135,  1.12406718,  1.88638286,  2.12218173],
       [ 5.45074455,  4.69836867,  1.15350985,  3.2521589 ]])

In [0]:
arr1 = np.zeros((3,4))

In [91]:
arr_inv = 1 / arr1

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [92]:
arr_inv #keyword inf denotes infinite value (divide by zero)

array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [93]:
np.isinf(arr_inv[0,0]) #returns true if given element is infinite.

True