<a href="https://colab.research.google.com/github/ShrayankM/FoundationsOFDataScience/blob/master/Basics_Of_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Checking Performance of Lists

In [0]:
N = 100000000

In [2]:
%%time
list_ = list(range(N))
for i in range(N):
    list_[i] = list_[i] * list_[i]

CPU times: user 19.3 s, sys: 2.46 s, total: 21.8 s
Wall time: 21.8 s


In [3]:
%%time
list_ = list(range(N))
list_ = [item * item for item in list_]

CPU times: user 9.17 s, sys: 4.62 s, total: 13.8 s
Wall time: 13.8 s


In [4]:
%%time
list_ = list(range(N))
list_ = map(lambda x: x * x,list_)

CPU times: user 3.11 s, sys: 4.42 s, total: 7.54 s
Wall time: 7.53 s


In [5]:
%%time
list_ = list(range(N))
list_sum = 0
for i in range(N):
    list_sum = list_sum + list_[i]

CPU times: user 15.6 s, sys: 1.53 s, total: 17.1 s
Wall time: 17.1 s


In [6]:
%%time
list_ = list(range(N))
list_sum = sum(list_)

CPU times: user 3.1 s, sys: 1.54 s, total: 4.64 s
Wall time: 4.64 s


In [0]:
import numpy as np

In [11]:
%%time
arr = np.arange(N)
arr = arr * arr

CPU times: user 305 ms, sys: 248 ms, total: 552 ms
Wall time: 556 ms


In [12]:
%%time
arr = np.arange(N)
arr_sum = np.sum(arr)

CPU times: user 291 ms, sys: 0 ns, total: 291 ms
Wall time: 292 ms


#Creating Numpy Arrays

In [13]:
arr = np.arange(5)
print(arr,type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [15]:
arr = np.array([0,2,4,6,8])

[0 2 4 6 8]


In [17]:
arr.dtype #tells the type of data items stored by arr

dtype('int64')

In [18]:
arr.ndim #show number of dimensions

1

In [20]:
arr.shape

(5,)

In [21]:
arr.size #total no of elements in array

5

In [22]:
arr.itemsize #no. of bytes required to store one data item in array(8-Bytes for integer)

8

In [0]:
arr = np.array([0.0,2,4,6,8])

In [24]:
arr.dtype

dtype('float64')

In [0]:
arr2d = np.array([
                  [1,2,3],
                  [4,5,6],
])

In [26]:
arr2d.shape #newly added dimension comes first

(2, 3)

In [0]:
arr3d = np.array([
                  [
                   [1,2,3],
                   [4,5,6],
                   [7,8,9]
                  ],
                  [
                   [10,11,12],
                   [13,14,15],
                   [16,17,18]
                  ],
])

In [32]:
arr3d.ndim

3

In [33]:
arr3d.shape

(2, 3, 3)

In [35]:
np.ones((3,4)) #takes argument as shape of ndArray

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
5 * np.ones((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [37]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [39]:
np.random.randn(2,3) #distributes the number in a normal distribution with data having (mean 0) and (variance 1)

array([[-0.94935018, -1.1972542 ,  1.36619297],
       [ 0.30785254,  0.17500633, -0.1210942 ]])

In [43]:
np.random.randn(2,3,3)

array([[[ 1.04160365,  0.86363365,  2.45597719],
        [-0.86217758, -0.19277806,  1.32313761],
        [ 1.0790386 , -0.83080513, -3.21755375]],

       [[-0.4129863 , -0.4355089 ,  0.05824224],
        [-0.00683623, -0.14133291, -0.47534548],
        [-0.88545028, -0.95103892, -1.25337525]]])

In [45]:
np.random.rand(2,3) #random numbers between 0 and 1

array([[0.58804454, 0.53350661, 0.00772175],
       [0.70030087, 0.94963703, 0.2241117 ]])

In [46]:
np.random.rand(1,10)

array([[0.89290383, 0.18368335, 0.31119357, 0.6294008 , 0.7521247 ,
        0.40004987, 0.22160027, 0.02558675, 0.10916622, 0.43081003]])

In [47]:
np.random.randint(0,100,(2,3)) #random integers between 0 and 100 in the given shape (2,3)

array([[80, 65, 92],
       [97, 97, 83]])

In [48]:
np.arange(7,71,7) #arg1 - smallNumber , arg2 - biggerNumber, arg3 - stepSize

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [54]:
np.linspace(7,70,10) #linearaly separated 5 numbers between 0 and 10

array([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70.])

In [57]:
str_arr = np.array(['1.2','2.4','4.5','6.6','9.5'])
float_arr = np.array(str_arr,dtype=float)
float_arr.dtype

dtype('float64')