<a href="https://colab.research.google.com/github/ShrayankM/FoundationsOFDataScience/blob/master/Stats_With_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Statistics

In [0]:
import numpy as np

In [0]:
arr = np.random.rand(100000)

In [0]:
arr

array([0.85858294, 0.94594466, 0.77792467, ..., 0.47175924, 0.11552997,
       0.16489758])

In [0]:
np.amin(arr)

7.306564619558031e-06

In [0]:
np.amax(arr)

0.999989835278102

In [0]:
np.mean(arr)

0.499657286419829

In [0]:
np.var(arr)

0.08341731899350112

In [0]:
np.std(arr)

0.28882056539225376

In [0]:
np.median(arr)

0.4991594735310446

In [0]:
np.percentile(arr,50)

0.4991594735310446

In [0]:
np.percentile(arr,25)

0.248890494387795

In [0]:
np.percentile(arr,75)

0.7508810644152806

In [0]:
%%time
iqr = np.percentile(arr,75) - np.percentile(arr,25)
print(iqr)

0.5019905700274856
CPU times: user 2.64 ms, sys: 2.89 ms, total: 5.53 ms
Wall time: 8.59 ms


In [0]:
%%time
quartiles = np.percentile(arr,[25,75])
iqr = quartiles[1] - quartiles[0]
print(iqr)

0.5019905700274856
CPU times: user 3.76 ms, sys: 0 ns, total: 3.76 ms
Wall time: 4.69 ms


In [0]:
(arr - np.mean(arr))/np.std(arr)

array([ 1.24272886,  1.54520636,  0.96346112, ..., -0.09659301,
       -1.32998602, -1.15905772])

In [0]:
np.histogram(arr) #first array gives frequency of points and second the bins

(array([10044, 10053,  9930, 10035, 10027,  9931,  9918, 10066, 10071,
         9925]),
 array([7.30656462e-06, 1.00005559e-01, 2.00003812e-01, 3.00002065e-01,
        4.00000318e-01, 4.99998571e-01, 5.99996824e-01, 6.99995077e-01,
        7.99993330e-01, 8.99991582e-01, 9.99989835e-01]))

In [0]:
np.histogram(arr,bins=5)

(array([20097, 19965, 19958, 19984, 19996]),
 array([7.30656462e-06, 2.00003812e-01, 4.00000318e-01, 5.99996824e-01,
        7.99993330e-01, 9.99989835e-01]))

In [0]:
np.histogram(arr,bins=[0.0,0.25,0.5,0.75,1.0]) #custom bins(4)

(array([25096, 24993, 24831, 25080]), array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

In [0]:
bins=[0.0,0.25,0.5,0.75,1.0]

In [0]:
np.digitize(arr,bins) #mapping of points to their specific bins

array([4, 4, 4, ..., 2, 1, 1])

In [0]:
arr1 = np.random.randint(0,10,(10))

In [0]:
arr1

array([5, 9, 7, 9, 2, 5, 7, 7, 3, 3])

In [0]:
bins = [0,6,10]

In [0]:
np.digitize(arr1,bins)

array([1, 2, 2, 2, 1, 1, 2, 2, 1, 1])

In [0]:
arr1 = np.random.randint(50,80,100) #weight in kgs
arr2 = np.random.randint(150,185,100) #height in cms
arr3 = np.random.randint(17,22,100) #age in years

In [0]:
np.concatenate((arr1,arr2,arr3))

array([ 57,  78,  61,  79,  57,  60,  70,  71,  56,  70,  58,  62,  71,
        56,  65,  79,  51,  68,  67,  66,  72,  69,  56,  67,  67,  70,
        67,  77,  54,  69,  76,  69,  66,  57,  53,  79,  74,  74,  62,
        64,  51,  64,  66,  79,  74,  57,  55,  58,  70,  65,  77,  51,
        67,  52,  62,  78,  75,  74,  73,  52,  51,  66,  59,  75,  63,
        51,  74,  64,  74,  64,  55,  71,  65,  72,  62,  62,  65,  59,
        76,  53,  52,  70,  75,  55,  69,  78,  75,  57,  67,  55,  78,
        57,  69,  55,  74,  66,  52,  57,  62,  52, 164, 168, 153, 178,
       174, 173, 180, 182, 183, 163, 165, 176, 158, 152, 156, 157, 156,
       182, 182, 162, 170, 177, 173, 184, 173, 171, 164, 162, 154, 156,
       171, 176, 181, 170, 150, 153, 180, 161, 184, 178, 155, 170, 157,
       165, 158, 156, 174, 176, 158, 157, 159, 180, 158, 179, 162, 184,
       183, 179, 178, 180, 163, 162, 166, 152, 155, 171, 161, 167, 178,
       161, 169, 173, 179, 173, 183, 179, 150, 162, 166, 151, 16

In [0]:
np.concatenate((arr1,arr2,arr3)).shape

(300,)

In [0]:
np.vstack((arr1,arr2,arr3))

array([[ 57,  78,  61,  79,  57,  60,  70,  71,  56,  70,  58,  62,  71,
         56,  65,  79,  51,  68,  67,  66,  72,  69,  56,  67,  67,  70,
         67,  77,  54,  69,  76,  69,  66,  57,  53,  79,  74,  74,  62,
         64,  51,  64,  66,  79,  74,  57,  55,  58,  70,  65,  77,  51,
         67,  52,  62,  78,  75,  74,  73,  52,  51,  66,  59,  75,  63,
         51,  74,  64,  74,  64,  55,  71,  65,  72,  62,  62,  65,  59,
         76,  53,  52,  70,  75,  55,  69,  78,  75,  57,  67,  55,  78,
         57,  69,  55,  74,  66,  52,  57,  62,  52],
       [164, 168, 153, 178, 174, 173, 180, 182, 183, 163, 165, 176, 158,
        152, 156, 157, 156, 182, 182, 162, 170, 177, 173, 184, 173, 171,
        164, 162, 154, 156, 171, 176, 181, 170, 150, 153, 180, 161, 184,
        178, 155, 170, 157, 165, 158, 156, 174, 176, 158, 157, 159, 180,
        158, 179, 162, 184, 183, 179, 178, 180, 163, 162, 166, 152, 155,
        171, 161, 167, 178, 161, 169, 173, 179, 173, 183, 179, 150, 16

In [0]:
np.vstack((arr1,arr2,arr3)).shape

(3, 100)

In [0]:
arr2d = np.vstack((arr1,arr2,arr3))

In [0]:
np.amin(arr2d,axis=1)

array([ 51, 150,  17])

#Mean Subracted array ha zero mean

In [0]:
arr = np.random.rand(1000)
mean = np.mean(arr)

In [0]:
arr1 = arr - mean
np.mean(arr1)

-1.6431300764452316e-17

In [0]:
for i in range(1,16):
    arr1 = arr[0:i]
    print(i,np.mean(arr1))

1 0.7780586082717963
2 0.6297736842859395
3 0.6885144056534257
4 0.577407272209282
5 0.4719359683858877
6 0.5237228078459174
7 0.5629158617682414
8 0.522080295796073
9 0.5285347542274893
10 0.5593337734957107
11 0.5114138698654592
12 0.5336559908220244
13 0.4971438017072144
14 0.5044168232157908
15 0.5004436982954555


In [0]:
means = np.cumsum(arr)/np.arange(1,1001)

In [0]:
means[1:16]

array([0.62977368, 0.68851441, 0.57740727, 0.47193597, 0.52372281,
       0.56291586, 0.5220803 , 0.52853475, 0.55933377, 0.51141387,
       0.53365599, 0.4971438 , 0.50441682, 0.5004437 , 0.48361872])

#Effect of outliers on mean and median

In [0]:
arr = np.random.randint(1,100,100)

In [0]:
np.mean(arr)

50.18

In [0]:
np.median(arr)

49.5

In [0]:
arr = np.append(arr,[1000,2000])

In [0]:
np.mean(arr)

78.6078431372549

In [0]:
np.median(arr)

51.0

#Effect of Scaling arrays on mean and median

In [0]:
arr = np.random.rand(100)

In [0]:
np.mean(arr)

0.4781674018405614

In [0]:
np.median(arr)

0.48962072087263714

In [0]:
arr1 = 2.5 * arr + 0.65 

In [0]:
np.mean(arr1)

1.8454185046014036

In [0]:
np.median(arr1)

1.8740518021815928

In [0]:
print(np.mean(arr1), 2.5 * np.mean(arr) + 0.65)

1.8454185046014036 1.8454185046014033


In [0]:
print(np.median(arr1), 2.5 * np.median(arr) + 0.65)

1.8740518021815928 1.8740518021815928


In [0]:
print(np.var(2.5 * arr + 0.65),2.5*2.5*np.var(arr))

0.483547941799492 0.4835479417994919


In [0]:
print(np.std(2.5 * arr + 0.65),2.5*np.std(arr))

0.6953761153501693 0.6953761153501693
