<a href="https://colab.research.google.com/github/ShrayankM/FoundationsOFDataScience/blob/master/Week_8_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
scores_data = np.genfromtxt("cric_data.tsv",skip_header=1,usecols=(1,2,3))

In [4]:
scores_data.shape

(225, 3)

In [0]:
sachins_scores = scores_data[:,0]

In [0]:
rahuls_score = scores_data[:,1]

In [0]:
indias_score = scores_data[:,2]

#1) Mean, Median, IQR for Sachin , Rahul , India

In [11]:
print("Sachins Mean Score ",np.mean(sachins_scores))
print("Sachins Scores Median ",np.median(sachins_scores))

Sachins Mean Score  39.87555555555556
Sachins Scores Median  27.0


In [0]:
sachins_quartiles = np.percentile(sachins_scores,[25,50,75])

In [13]:
print("Sachins Scores IQR ", sachins_quartiles[2] - sachins_quartiles[0])

Sachins Scores IQR  57.0


In [15]:
print("Rahuls Mean Score ",np.mean(rahuls_score))
print("Rahuls Scores Median ",np.median(rahuls_score))

Rahuls Mean Score  32.062222222222225
Rahuls Scores Median  22.0


In [0]:
rahuls_quartiles = np.percentile(rahuls_score,[25,50,75])

In [18]:
print("Rahuls Scores IQR ", rahuls_quartiles[2] - rahuls_quartiles[0])

Rahuls Scores IQR  46.0


#2) Histogram of Sachins Score with 10 bins

In [0]:
bins = [0,20,40,60,80,100,120,140,160,180,200]

In [21]:
np.histogram(sachins_scores,bins)

(array([100,  40,  24,  17,  18,  11,   7,   7,   0,   1]),
 array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200]))

#3) Mean of Sachin's Score grouped by 25 matches

In [29]:
%%time
i = 0
while i < 225:
    print(np.mean(sachins_scores[i:i+25]))
    i = i + 25

33.96
49.4
38.48
40.16
39.36
38.2
44.6
39.52
35.2
CPU times: user 2.34 ms, sys: 898 µs, total: 3.24 ms
Wall time: 2.49 ms


#4) Mean of Sachin's Score when he scores a century

In [32]:
%%time
century_plus_scores = sachins_scores[sachins_scores >= 100]
print("Mean of Century Plus Score",np.mean(century_plus_scores))

Mean of Century Plus Score 125.0
CPU times: user 612 µs, sys: 67 µs, total: 679 µs
Wall time: 517 µs


#5) Find the mean of Sachin's Score when rahul scores less than 10

In [36]:
%%time
sachin_new_scores = sachins_scores[rahuls_score < 10]
print("Mean of Less than 10 Score ", np.mean(sachin_new_scores))

Mean of Less than 10 Score  40.74285714285714
CPU times: user 1.03 ms, sys: 845 µs, total: 1.87 ms
Wall time: 1.74 ms


#6) Find the mean of Sachin's Score based on India's Quartile Score

In [43]:
%%time
quartiles_india = np.percentile(indias_score,[25,50,75,100])
sachins_q1 = sachins_scores[indias_score < quartiles_india[0]]
sachins_q2 = sachins_scores[indias_score < quartiles_india[1]]
sachins_q3 = sachins_scores[indias_score < quartiles_india[2]]
sachins_q4 = sachins_scores[indias_score < quartiles_india[3]]
print(quartiles_india)
print("Quater_1 mean Score",np.mean(sachins_q1))
print("Quater_2 mean Score",np.mean(sachins_q2))
print("Quater_3 mean Score",np.mean(sachins_q3))
print("Quater_4 mean Score",np.mean(sachins_q4))

[175. 216. 273. 499.]
Quater_1 mean Score 19.672727272727272
Quater_2 mean Score 28.18018018018018
Quater_3 mean Score 31.688622754491018
Quater_4 mean Score 39.799107142857146
CPU times: user 1.78 ms, sys: 1.99 ms, total: 3.77 ms
Wall time: 2.9 ms


#7) For every Match find who scored more Sachin or Rahul

In [51]:
%%time
matches_sachin_more = indias_score[scores_data[:,0] > scores_data[:,1]]
matches_rahul_more  = indias_score[scores_data[:,1] > scores_data[:,0]]
print("Matches where Sachin Scored More, " ,np.count_nonzero(matches_sachin_more))
print("Matches where Rahul Scored More, ", np.count_nonzero(matches_rahul_more))

Matches where Sachin Scored More,  111
Matches where Rahul Scored More,  106
CPU times: user 818 µs, sys: 0 ns, total: 818 µs
Wall time: 825 µs


#8) How many more runs does Sachin Score on an average after scoring x runs?

In [0]:
def average_after_x(x_score):
    scores = sachins_scores[sachins_scores >= x_score]
    scores = scores - x_score
    print("After Scoring ",x_score," runs on an average he scores, ",np.mean(scores)," more runs.")

In [65]:
%%time
average_after_x(0)
average_after_x(5)
average_after_x(40)
average_after_x(60)

After Scoring  0  runs on an average he scores,  39.87555555555556  more runs
After Scoring  5  runs on an average he scores,  45.61363636363637  more runs
After Scoring  40  runs on an average he scores,  44.05882352941177  more runs
After Scoring  60  runs on an average he scores,  38.67213114754098  more runs
CPU times: user 4.1 ms, sys: 0 ns, total: 4.1 ms
Wall time: 4.79 ms
