<a href="https://colab.research.google.com/github/ShrayankM/FoundationsOFDataScience/blob/master/Week_8_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Statement 1**

In [0]:
import numpy as np

In [0]:
matrix1 = np.random.randint(1,100,(100,100))
matrix2 = np.random.randint(1,100,(100,100))

In [0]:
result_matrix = np.zeros((100,100))

In [10]:
%%time
for i in range(100):
    for j in range(100):
        for k in range(100):
            result_matrix[i][j] = result_matrix[i][j] + matrix1[i][k] * matrix2[k][j]
print(result_matrix)

[[259881. 278524. 273987. ... 267196. 242877. 274640.]
 [251373. 249786. 264852. ... 263626. 238802. 249486.]
 [243742. 251440. 255435. ... 240414. 224126. 242231.]
 ...
 [223995. 230738. 229110. ... 232823. 224458. 255092.]
 [264807. 272094. 261129. ... 261083. 239231. 262932.]
 [248865. 268556. 264626. ... 266909. 243469. 262984.]]
CPU times: user 1.7 s, sys: 1.02 ms, total: 1.7 s
Wall time: 1.71 s


In [11]:
%%time
result_matrix = np.dot(matrix1,matrix2)
print(result_matrix)

[[259881 278524 273987 ... 267196 242877 274640]
 [251373 249786 264852 ... 263626 238802 249486]
 [243742 251440 255435 ... 240414 224126 242231]
 ...
 [223995 230738 229110 ... 232823 224458 255092]
 [264807 272094 261129 ... 261083 239231 262932]
 [248865 268556 264626 ... 266909 243469 262984]]
CPU times: user 1.82 ms, sys: 1.08 ms, total: 2.9 ms
Wall time: 2.79 ms


**Statement 2**

In [0]:
w = np.random.rand(3,2)
x = np.random.rand(2,4)

In [0]:
z = np.dot(w,x)

In [0]:
def sigma_operation(z):
    sigma = 1/(1 + np.exp(-z))
    return sigma

In [20]:
%%time
sigma = sigma_operation(z)
print(sigma)

[[0.53094755 0.58801796 0.5919927  0.57033136]
 [0.61438305 0.79804535 0.7208438  0.71234301]
 [0.57574982 0.70885117 0.68035653 0.65501778]]
CPU times: user 788 µs, sys: 989 µs, total: 1.78 ms
Wall time: 1.32 ms


**Statement 3**

In [0]:
n = 10
M = np.random.randint(1,100,(n,n))

In [0]:
M = M.reshape(n*n,)

In [71]:
M

array([80, 18, 98, 86, 36, 45, 29, 85, 55, 49, 25, 49, 57, 29, 19, 78, 64,
       82, 12,  1,  1, 47, 98, 46, 26, 55, 41, 28, 14, 58, 53, 24, 16, 79,
       83, 93, 61, 22,  3, 69, 24, 85, 54, 61, 71, 43, 55,  8, 66,  8, 62,
       59, 38, 55, 48, 34,  8, 91, 49, 58, 44, 14, 53, 48, 80, 39, 59, 42,
       24, 35,  2,  1, 99, 71, 74, 71, 58,  3, 57, 29, 87, 64,  5,  4, 48,
       28, 95, 75, 44,  4, 40, 79, 57, 76, 23, 28, 96, 88, 17, 56])

In [72]:
%%time
sum_M = 0
for i in range(len(M)):
    sum_M = sum_M + M[i]
print(sum_M/len(M))

48.08
CPU times: user 347 µs, sys: 0 ns, total: 347 µs
Wall time: 531 µs


In [73]:
%%time
sum_M = np.sum(M)
print(sum_M/len(M))

48.08
CPU times: user 479 µs, sys: 34 µs, total: 513 µs
Wall time: 412 µs


In [32]:
%%time
mean_of_M = np.mean(M)
print(mean_of_M)

49.4
CPU times: user 359 µs, sys: 0 ns, total: 359 µs
Wall time: 288 µs


In [45]:
%%time
std_of_M = np.sqrt((np.sum(M**2 - mean_of_M**2 ))/(len(M) - 1))
print(std_of_M)

31.095161856936702
CPU times: user 673 µs, sys: 976 µs, total: 1.65 ms
Wall time: 1.54 ms


In [46]:
%%time
std_of_M = np.std(M)
print(std_of_M)

30.93929540244897
CPU times: user 514 µs, sys: 0 ns, total: 514 µs
Wall time: 416 µs


In [48]:
%%time
z_scores = (M - np.mean(M)) / np.std(M)
print(z_scores)

[ 0.76278402  0.98903351 -1.5320323   0.73046266  1.02135487  0.27796367
  0.21332095  0.73046266  1.11831894 -1.07953331 -1.56435366  1.53849657
  1.18296165  0.01939281  0.63349859 -0.75631974 -1.27346145  0.37492774
 -0.7886411  -1.49971095  1.50617522  1.60313929 -1.07953331 -0.59471296
  0.53653452 -0.62703432 -0.65935567 -0.69167703  1.4415325  -0.56239161
 -0.56239161 -0.14221397 -1.27346145 -0.85328381 -1.20881874 -0.82096246
  1.02135487 -0.88560517  1.34456844  0.27796367  0.98903351 -0.82096246
  1.02135487 -0.40078482 -0.56239161  1.1506403   1.18296165  0.11635688
 -0.20685668 -1.49971095 -1.40274688 -1.43506823  0.76278402  1.40921115
  0.08403553 -0.69167703 -0.53007025 -0.17453533 -0.10989261 -1.30578281
 -1.56435366 -1.56435366  1.1506403   0.27796367  0.73046266  1.02135487
 -0.33614211  1.4415325  -0.75631974  0.01939281  1.27992572  0.89206944
  1.11831894  1.21528301  0.73046266  0.76278402  0.98903351  1.60313929
 -1.56435366 -0.43310618 -0.49774889 -0.59471296 -1

In [49]:
print("Mean of Z_score_data",np.mean(z_scores))
print("Std of Z_score_data",np.std(z_scores))

Mean of Z_score_data 6.827871601444713e-17
Std of Z_score_data 1.0


In [50]:
print("Mean of M data",np.mean(M))
print("Std of M data",np.std(M))

Mean of M data 49.4
Std of M data 30.93929540244897


**Statement 4**

In [0]:
def make_vector(ndim):
    return np.random.rand(2,ndim)

In [0]:
V = make_vector(3)

In [0]:
def find_magnitude(vector):
    return np.sqrt(np.sum((vector[0] - vector[1])**2))

In [57]:
print("Magnitude of V,",find_magnitude(V))

Magnitude of V, 0.6735832130758842


In [0]:
V_custom = np.array([
    [1,1],
    [5,3]
]
)

In [60]:
V_custom.shape

(2, 2)

In [61]:
print("Magnitude of V_custom,",find_magnitude(V_custom))

Magnitude of V_custom, 4.47213595499958


**Statement 5**

In [0]:
y_bar = np.random.rand(10)
y = np.random.randint(0,2,10)

In [0]:
O = -np.sum(y * np.log(y_bar) + (1 -y) * np.log(1 - y_bar))/10

In [68]:
O

1.2821901438491774